config/routes.rb
MailyHerald::Webui::Engine.routes.draw do
	root to: 'dashboard#index'
  resources "logs" do
    member do
      get "preview"
    end
  end
  resources "lists" do
    member do
      post "subscribe/:entity_id", action: :subscribe, as: :subscribe_to
      post "unsubscribe/:entity_id", action: :unsubscribe, as: :unsubscribe_from
      get "context_attributes(/:context)", action: :context_attributes, as: :context_attributes
    end
  end
  resources "subscriptions" do
    member do
      post "toggle"
    end
  end
  resources "ad_hoc_mailings" do
    collection do 
      get "archived"
      post "update_form"
    end
    member do
      post "toggle"
      post "deliver/(:entity_id)", action: :deliver, as: :deliver
      get "preview/:entity_id", action: :preview, as: :preview
    end
  end
  resources "one_time_mailings" do
    collection do 
      get "archived"
      post "update_form"
    end
    member do
      post "toggle"
      get "preview/:entity_id", action: :preview, as: :preview
    end
  end
  resources "periodical_mailings" do
    collection do 
      get "archived"
      post "update_form"
    end
    member do
      post "toggle"
      get "preview/:entity_id", action: :preview, as: :preview
    end
  end
  resources "sequences" do
    resources "sequence_mailings", as: "mailings", path: "mailings", except: [:index] do
      collection do 
        get "archived"
        post "update_form"
      end
      member do
        post "toggle"
        get "preview/:entity_id", action: :preview, as: :preview
      end
    end
    collection do 
      get "archived"
      post "update_form"
    end
    member do
      post "toggle"
    end
  end

  post "settings/:setting/switch", to: "sessions#switch_setting", as: "switch_setting"






  #resources "sequences" do
    #resources "mailings", :only => [:new, :create], :controller => "mailings", :mailing_type => :sequence
    #member do
      #get "subscription/:entity_id", :to => :subscription, :as => :subscription
      #get "subscription/:entity_id/toggle", :to => :toggle_subscription, :as => :toggle_subscription
      #get "toggle", :to => :toggle, :as => :toggle
    #end
  #end
  #resources "mailings", :except => [:new, :create] do
    #member do
      #get "subscription/:entity_id", :to => :subscription, :as => :subscription
      #get "subscription/:entity_id/toggle", :to => :toggle_subscription, :as => :toggle_subscription
      #get "dashboard/:entity_id", :to => :dashboard, :as => :dashboard
      #get "deliver/(:entity_id)", :to => :deliver, :as => :deliver
      #get "toggle", :to => :toggle, :as => :toggle
      #get "preview/:subscription_id", :to => :preview, :as => :preview
    #end
    #collection do
      #get "context_attributes/(:context_name)", :to => :context_attributes, :as => :context_attributes
    #end
  #end
  #resources "sequences_mailings", :only => [:index, :new], :controller => "mailings", :mailing_type => :sequence
  #resources "one_time_mailings", :only => [:index, :new, :create], :controller => "mailings", :mailing_type => :one_time
  #resources "periodical_mailings", :only => [:index, :new, :create], :controller => "mailings", :mailing_type => :periodical
  #resources "subscription_groups" do
    #member do
      #get "subscription/:subscription_id/toggle", :to => :toggle_subscription, :as => :toggle_subscription
    #end
  #end
  #resources "dashboard", :only => [:index, :show] do
    #collection do 
      #get "time_travel"
      #get "forget"
    #end
  #end
end

app/controllers/maily_herald/webui/ad_hoc_mailings_controller.rb
module MailyHerald
	class Webui::AdHocMailingsController < Webui::MailingsController
    add_breadcrumb :label_ad_hoc_mailing_plural, Proc.new{ ad_hoc_mailings_path }
    set_menu_item :ad_hoc_mailings

    def archived 
      add_breadcrumb view_context.tw("#{controller_name}.archived.label")
      
      super
    end

    def show
      super
    end

    def deliver
      find_item

      if params[:entity_id]
        @e = @item.list.context.scope.find(params[:entity_id])
        @item.schedule_delivery_to @e

        render_containers ["schedules"]
        render_update
      else
        @item.schedule_delivery_to_all

        render_containers ["schedules"]
        render_update
      end
    end
  end
end

app/controllers/maily_herald/webui/application_controller.rb
module MailyHerald
  module Webui
    class ApplicationController < ActionController::Base
      include MailyHerald::Webui::Breadcrumbs::ControllerExtensions
      include MailyHerald::Webui::MenuManager::ControllerExtensions

      helper SmartListing::Helper
      helper_method :settings

      def settings
        Settings.new(cookies)
      end

      def log_scope
        if settings.show_skipped?
          MailyHerald::Log.all
        else
          MailyHerald::Log.not_skipped
        end
      end
    end
  end
end

app/controllers/maily_herald/webui/dashboard_controller.rb
module MailyHerald
	class Webui::DashboardController < Webui::ApplicationController
    include SmartListing::Helper::ControllerExtensions
    helper  SmartListing::Helper

    add_breadcrumb :label_dashboard, Proc.new{ lists_path }
    set_menu_item :dashboard

		def index
      @period = case params[:period]
                when "week"
                  1.week
                when "6months"
                  6.months
                when "year"
                  1.year
                else #month
                  1.month
                end
      @time = Time.now

      smart_listing_create(:logs, logs(:processed), :partial => "maily_herald/webui/logs/items", default_sort: {processing_at: "desc"})
      smart_listing_create(:scheduled_logs, MailyHerald::Log.scheduled, :partial => "maily_herald/webui/logs/items", default_sort: {processing_at: "asc"})

      @total_count = log_scope.count
      @processed_count = logs(:processed).count
      @delivered_count = logs(:delivered).count
      @skipped_count = logs(:skipped).count
      @failed_count = logs(:error).count

      days = @period / 1.day
      @delivered = {}
      @failed = {}
      @skipped = {}

      for i in 0..days
        @delivered[(@time - i.days).strftime("%Y-%m-%d")] = 0
        @failed[(@time - i.days).strftime("%Y-%m-%d")] = 0
        @skipped[(@time - i.days).strftime("%Y-%m-%d")] = 0
      end


      logs(:delivered).each do |l| 
        @delivered[l.processing_at.strftime("%Y-%m-%d")] ||= 0
        @delivered[l.processing_at.strftime("%Y-%m-%d")] += 1
      end
      logs(:error).each do |l| 
        @failed[l.processing_at.strftime("%Y-%m-%d")] ||= 0
        @failed[l.processing_at.strftime("%Y-%m-%d")] += 1
      end
      logs(:skipped).each do |l| 
        @skipped[l.processing_at.strftime("%Y-%m-%d")] ||= 0
        @skipped[l.processing_at.strftime("%Y-%m-%d")] += 1
      end
		end

    private

    def logs state, period = nil
      period ||= @period

      log_scope.send(state).where("processing_at > (?)", @time - period)
    end
	end
end

app/controllers/maily_herald/webui/dispatches_controller.rb
module MailyHerald
	class Webui::DispatchesController < Webui::ResourcesController
    def index
      super do |scope|
        scope.not_archived
      end
    end

    def archived 
      self.class.superclass.instance_method(:index).bind(self).call do |scope|
        scope.archived
      end

      render "index"
    end

    def update_form
      new
      @item.attributes = item_params
    end

    def destroy
      @item.archive!

      render_containers ["details", "subscribers"]
      render_update
    end

    def toggle
      find_item

      unless @item.enabled?
        @item.enable!
      else
        @item.disable!
      end

      render_containers ["details", "subscribers"]
      render_update
    end
  end
end

app/controllers/maily_herald/webui/logs_controller.rb
module MailyHerald
	class Webui::LogsController < Webui::ResourcesController
    add_breadcrumb :label_log_plural, Proc.new{ logs_path }
    set_menu_item :logs

    def preview
      @log = MailyHerald::Log.find params[:id]

      render layout: "maily_herald/webui/modal"
    end

    protected

    def resource_spec
      @resource_spec ||= Webui::ResourcesController::Spec.new.tap do |spec|
        spec.klass = MailyHerald::Log
      end
    end
  end
end

app/controllers/maily_herald/webui/one_time_mailings_controller.rb
module MailyHerald
	class Webui::OneTimeMailingsController < Webui::MailingsController
    add_breadcrumb :label_one_time_mailing_plural, Proc.new{ one_time_mailings_path }
    set_menu_item :one_time_mailings

    def archived 
      add_breadcrumb view_context.tw("#{controller_name}.archived.label")
      
      super
    end

    def show
      super
    end

    protected

    def set_resource_spec
      spec = super
      spec.params.push(:start_at)
      spec.update_containers["schedules"] = true
      spec.containers_order = ["details", "template", "subscribers", "schedules", "logs"]
      spec
    end

    def action_dependencies *containers
      super do |container|
        case container
        when "schedules"
          @schedules = smart_listing_create(:schedules, @item.logs.scheduled, :partial => "maily_herald/webui/logs/items", default_sort: {processing_at: "asc"})
        end
      end
    end
  end
end

app/helpers/maily_herald/webui/application_helper.rb
module MailyHerald
  module Webui
    module ApplicationHelper
      include MailyHerald::Webui::Breadcrumbs::HelperExtensions

      def render_main_menu
        content_tag(:ul, :class => "nav nav-main") do
          menu_manager.items.each do |i|
            title = i[:title] || i[:name]
            title = tw(title) if title.is_a?(Symbol)

            url = i[:url]
            url = self.instance_eval(&url) if url.is_a?(Proc)

            classes = []
            classes << "active" if current_menu_item == i[:name]

            concat(content_tag(:li, :class => classes) do
              concat(link_to(title, url))
            end)
          end
        end
      end

      def render_breadcrumbs
        if has_breadcrumbs?
          content_tag(:ul, :class => "breadcrumb") do
            @breadcrumbs.each do |b|
              unless @breadcrumbs.last == b
                concat(content_tag(:li) do
                  concat(link_to(b[:name].is_a?(Symbol) ? tw(b[:name]) : b[:name], b[:url]))
                end)
              else
                concat(content_tag(:li, :class => "active") do
                  concat(b[:name].is_a?(Symbol) ? tw(b[:name]) : b[:name])
                end)
              end
            end
          end
        end
      end

      def link_to_context_attributes_overview list, options = {}
        link_to context_attributes_list_path(id: list, context: list.context_name), data: {toggle: "modal", target: "#modal-generic"}, class: ["link link-help", options[:class]] do 
          html = concat(icon(:list))
          html.concat(" ").concat(list.context_name) if options[:text]
        end if list.try(:context_name)
      end

      def render_context_attributes_info list
        render partial: "maily_herald/webui/shared/context_attributes", locals: {list: list}
      end

      def display_context_attributes attributes
        content_tag(:ul) do
          attributes.each do |k, v|
            if v.is_a?(Hash)
              concat(content_tag(:li) do
                concat(k)
                concat(display_context_attributes(v))
              end)
            else
              concat(content_tag(:li, k))
            end
          end
        end
      end

      def content_for_expert
        yield if settings.expert_mode
      end

      def work_mode_t mode
        t(mode, {scope: [:maily_herald, :webui, :work_modes]})
      end

      def setting_t setting
        t(setting, {scope: [:maily_herald, :webui, :settings]})
      end

      def tw(key, options = {})
        t(key, {scope: [:maily_herald, :webui]}.merge(options))
      end

      def friendly_name obj
        return unless obj
        obj.respond_to?(:title) && obj.title.present? ? obj.title : obj.try(:name)
      end

      def form_for(object, options = {}, &block)
        options.reverse_merge!({builder: MailyHerald::Webui::FormBuilder})
        layout = case options[:layout]
                 when :inline
                   "form-inline"
                 when :horizontal
                   "form-horizontal"
                 end
        if layout
          options[:html] ||= {}
          options[:html][:class] = [options[:html][:class], layout].compact.join(" ")
        end

        super(object, options, &block)
      end

      def icon(icon, text="", html_options={})
        content_class = "fa fa-#{icon}"
        content_class << " #{html_options[:class]}" if html_options.key?(:class)
        html_options[:class] = content_class

        html = content_tag(:i, nil, html_options)
        html << " #{text}" unless text.blank?
        html.html_safe
      end

      def boolean_icon value, options = {}
        options = {
          :style => :check,
          :text => :active,
        }.merge(options)

        i = case options[:style]
            when :check
              value ? "check-square-o" : "square-o"
            when :toggle
              value ? "toggle-on" : "toggle-off"
            end

        text = case options[:text]
               when :active
                 value ? tw("commons.active") : tw("commons.inactive")
               when :enabled
                 value ? tw("commons.enabled") : tw("commons.disabled")
               when :yes
                 value ? tw("commons.positive") : tw("commons.negative")
               end

        icon(i, text)
      end

      def display_help_icon title, options = {}
        link_to "#", class: "link link-help", data: {toggle: "tooltip", placement: options[:placement] || "right"}, title: (options[:scope] ? tw("#{options[:scope]}.help.#{title}") : t(".help.#{title}")) do
          icon(:question)
        end
      end

      def filter_box field_name = :filter
        content_tag(:div, class: "filter filter-search") do
          concat(text_field_tag(field_name, params[field_name], class: "search form-control", placeholder: "Search...", autocomplete: "off"))
          concat(button_tag(class: "btn", type: "submit") do
            icon(:search)
          end)
        end
      end

      def setting_switcher setting
        link_to(switch_setting_path(setting), method: :post) do
          concat(icon(settings.get(setting) ? "toggle-on" : "toggle-off"))
          concat("&nbsp;".html_safe)
          concat(setting_t(setting))
        end
      end

      def smart_listing_config_profile
        :maily_herald
      end

      def display_timestamp t
        if t && settings.friendly_timestamps?
          content_tag(:abbr, tw((t > Time.now) ? "commons.time_in" : "commons.time_ago", time: distance_of_time_in_words(t, Time.now)), title: t)
        else
          t
        end
      end
    end
  end
end

app/helpers/maily_herald/webui/dashboard_helper.rb
module MailyHerald
  module Webui
    module DashboardHelper
      def history_graph_data
        h = {
          delivered: @delivered.to_json, 
          failed: @failed.to_json, 
        }
        h[:skipped] = @skipped.to_json if settings.show_skipped?
        h
      end
    end
  end
end

app/helpers/maily_herald/webui/dispatches_helper.rb
module MailyHerald
  module Webui
    module DispatchesHelper
      def display_dispatch_state s
        content_tag(:span) do 
          case s.state
          when :enabled
            boolean_icon true, style: :toggle, text: :enabled
          when :disabled
            boolean_icon false, style: :toggle, text: :enabled
          when :archived
            icon("archive", tw("commons.archived"))
          end
        end
      end
    end
  end
end

app/helpers/maily_herald/webui/lists_helper.rb
module MailyHerald
  module Webui
    module ListsHelper
      def display_list_scope_status list, entity
        if list.context.scope.exists?(entity)
          content_tag(:span, icon(:check, tw("commons.positive")))
        else
          content_tag(:span, icon(:times, tw("commons.negative")), class: "text-warning")
        end
      end
    end
  end
end

app/helpers/maily_herald/webui/logs_helper.rb
module MailyHerald
  module Webui
    module LogsHelper
      def log_actions log
        actions = []
        subscription = log.mailing.list.subscription_for(log.entity) if log.mailing && log.entity
        actions << {
          name:      :custom, 
          url:       subscription_path(subscription),
          icon:      "fa fa-book",
          title:     tw("label_subscription")
        } if subscription && !@item.is_a?(Subscription)
        actions << {
          name: :custom, 
          url: preview_log_path(log), 
          icon: "fa fa-file-o", 
          data: {
            toggle: "modal", 
            target: "#modal-generic"
          }
        }
      end

      def display_log_status log
        case log.status
        when :delivered
          content_tag(:span, icon(:check, tw("logs.status.delivered")), class: "text-success")
        when :skipped
          content_tag(:span, icon(:times, tw("logs.status.skipped")), class: "text-warning")
        when :error
          content_tag(:span, icon(:exclamation, tw("logs.status.error")), class: "text-danger")
        when :scheduled
          content_tag(:span, icon(:"clock-o", tw("logs.status.scheduled")), class: "text-muted")
        end
      end

      def display_log_skip_reason skip_reason
        tw("logs.skip_reason.#{skip_reason}") if skip_reason
      end
    end
  end
end

app/views/maily_herald/webui/mailings/_deliver.js.erb
$("#subscribers").smart_listing().fadeLoaded();

app/views/maily_herald/webui/mailings/_details.html.haml
= render partial: "header"

- if @item.disabled?
  .alert.alert-warning= tw("mailings.infos.disabled")
- elsif @item.archived?
  .alert.alert-info= tw("mailings.infos.archived")

.dl-horizontal
  - content_for_expert do
    %dt= tw("attributes.name")
    %dd= @item.name
  %dt= tw("attributes.title")
  %dd= @item.title

  %dt
    = tw("attributes.mailer")
    = display_help_icon :mailer_name, scope: "mailings"
  %dd= display_mailing_mailer @item.mailer_name

  %dt
    = @item.class.human_attribute_name(:from)
    = display_help_icon "from", scope: "mailings"
  %dd= display_mailing_from @item

  %dt= tw(:label_list)
  %dd= link_to friendly_name(@item.list), list_path(@item.list)


%p

= render_context_attributes_info @item.list

- if @item.one_time?
  %p

  .dl-horizontal
    %dt= @item.class.human_attribute_name(:start_at)
    %dd= display_mailing_start_at @item

- if @item.periodical?
  %p

  .dl-horizontal
    %dt= @item.class.human_attribute_name(:start_at)
    %dd= display_mailing_start_at @item

    %dt= @item.class.human_attribute_name(:period)
    %dd= display_mailing_period @item
- elsif @item.sequence?
  %p

  .dl-horizontal
    %dt= @item.class.human_attribute_name(:absolute_delay)
    %dd= display_mailing_absolute_delay @item


%p

.dl-horizontal
  %dt= tw("attributes.conditions")
  %dd= display_mailing_conditions @item
  %dt
    = tw("attributes.override_subscription")
    = display_help_icon("override_subscription", scope: "mailings")
  %dd
    = boolean_icon(@item.override_subscription, text: :yes)

%p

app/views/maily_herald/webui/mailings/_details_form.html.haml
- unless @item.new_record?
  = render partial: "header"

= form_for(@item, :as => :item, :layout => :horizontal, :remote => !@item.new_record?, :control_col => "col-sm-5", help_scope: "mailings", html: {class: "dispatch-form"}, data: {update_form_path: url_for(action: "update_form") }) do |f|
  - if f.object.new_record?
    %h2= tw("dispatches.general")

  - content_for_expert do
    = f.text_field :name
  = f.text_field :title
  = f.maily_mailer_select help: true
  = f.maily_from_field help: true
  - if @item.new_record? && !@item.sequence?
    = f.maily_list_select

    .form-group
      %label.control-label.col-sm-2= tw("attributes.context")
      .col-sm-5
        %p.help-block.context-name
          = link_to_context_attributes_overview(@item.list, text: true) || tw("dispatches.no_context")

  - if @item.one_time?
    = render partial: "form_one_time", locals: {f: f}
  - elsif @item.periodical?
    = render partial: "form_periodical", locals: {f: f}
  - elsif @item.sequence?
    = render partial: "form_sequence", locals: {f: f}

  = f.text_area :conditions
  = f.check_box :override_subscription

  - if f.object.new_record?
    .template-generic
      = render partial: "form_template_generic", locals: {f: f}
    .template-mailer
      = render partial: "form_template_mailer", locals: {f: f}

  - if @item.new_record?
    = f.buttons :create
  - else
    = f.buttons :save, :cancel

app/views/maily_herald/webui/mailings/_form.html.haml
= render partial: "details_form"

app/views/maily_herald/webui/mailings/_form_one_time.html.haml
= f.maily_start_at_field help: true

app/views/maily_herald/webui/mailings/_form_periodical.html.haml
= f.maily_start_at_field help: true
= f.maily_period_field

app/views/maily_herald/webui/mailings/_form_sequence.html.haml
= f.maily_absolute_delay_field

app/views/maily_herald/webui/mailings/_form_template_generic.html.haml
%h2
  = tw("mailings.template")
  = link_to_context_attributes_overview f.object.list

= f.text_field :subject
-#= f.text_field :sender
= f.text_area :template, rows: 15, control_col: "col-sm-10"

app/views/maily_herald/webui/mailings/_header.html.haml
%h1
  - if @item.sequence?
    = link_to @item.sequence do
      %span.resource-name= friendly_name @item.sequence
    &raquo;
  %span.resource-name= friendly_name @item
  - unless @item.locked?
    = link_to({action: "toggle", id: @item}, :remote => true, :class => "link link-sm dispatch-state", :confirm => @item.enabled? ? t(".disable_confirm") : t(".enable_confirm"), :method => :post) do
      = display_dispatch_state @item
    = link_to({action: "edit", id: @item}, :remote => true, :class => "link link-sm") do
      = icon(:pencil)
      = tw("commons.edit")
  - else
    %a.link.link-sm.text-warning{:data => {:toggle => "tooltip", :placement => "top"}, :title => tw("dispatches.locked_info")}
      = icon(:lock)
      = tw("commons.locked")
  - if @item.enabled? && @item.ad_hoc?
    = link_to({action: "deliver", id: @item}, :method => :post, :remote => true, :data => {:confirm => tw("ad_hoc_mailings.header.confirm_send_to_all")}, :class => "link link-sm") do
      = icon(:send)
      = tw("commons.send_to_all")
  - unless @item.locked? || @item.archived?
    = link_to({action: "destroy", id: @item}, :method => :delete, :remote => true, :data => {:confirm => t(".confirm_archive")}, :class => "link link-sm") do
      = icon(:archive)
      = tw("commons.archive")

app/views/maily_herald/webui/mailings/_list.html.haml
- unless smart_listing.empty?
  %table.table.table-striped
    %thead
      %tr 
        %th.col-md-3= tw("attributes.title")
        - if @sequence
          %th= MailyHerald::SequenceMailing.human_attribute_name(:absolute_delay)
        %th= tw("attributes.state")
        %th= tw(:label_list)
        %th= tw("attributes.mailer")
        %th
    %tbody
      - smart_listing.collection.each do |mailing|
        %tr
          %td= link_to_mailing mailing
          - if @sequence
            %td= distance_of_time_in_words(mailing.absolute_delay)
          %td= display_dispatch_state mailing
          %td= link_to friendly_name(mailing.list), list_path(mailing.list)
          %td= display_mailing_mailer mailing.mailer_name
          %td.actions
            .action-group= smart_listing_item_actions [{name: :show, url: url_for_mailing(mailing)}]

  = smart_listing.paginate 
  = smart_listing.pagination_per_page_links 
- else
  = t(".no_mailings")

app/views/maily_herald/webui/mailings/_template.html.haml
- if @item.generic_mailer?
  %h2.border
    = tw("mailings.template")
    - unless @item.locked?
      = link_to({action: "edit", id: @item, :edited_container => "template"}, :remote => true, :class => "link link-sm") do
        = icon(:pencil)
        = tw("commons.edit")
  .dl-horizontal
    %dt= tw("attributes.subject")
    %dd= @item.subject
  %br
  %pre= @item.template
  %br
- else
  %h2.border
    = tw("mailings.template")
  %p= tw("mailings.infos.non_generic_mailer", mailer: display_mailing_mailer(@item.mailer_name).html_safe, generic_mailer: display_mailing_mailer(:generic)).html_safe

app/views/maily_herald/webui/mailings/_template_form.html.haml
= form_for @item, :as => :item, :layout => :horizontal, :remote => !@item.new_record?, :control_col => "col-sm-5", html: {class: "edit-mailing-template-form"} do |f|
  = hidden_field_tag :edited_container, "template"
  - if @item.generic_mailer?
    = render partial: "form_template_generic", locals: {f: f}
  - else
    = render partial: "form_template_mailer", locals: {f: f}
  = f.buttons :save, :cancel

app/views/maily_herald/webui/mailings/preview.html.haml
- content_for :modal_title do
  = t(".title")

.box.noborder
  .dl-horizontal
    %dt= tw("attributes.mailing")
    %dd= friendly_name @item
    %dt= tw("attributes.entity")
    %dd= @e

.alert.alert-info= t(".info")

%pre= @mail

app/views/maily_herald/webui/mailings/update_form.js.erb
<% if @item.generic_mailer? %>
  $(".template-generic").show();
  $(".template-mailer").hide();
  var link = "<%= escape_javascript(link_to_context_attributes_overview(@item.list)) %>";
  if(link) {
    if($(".template-generic h2 a").length == 1) {
      $(".template-generic h2 a").replaceWith(link);
    } else {
      $(".template-generic h2").append(link);
    }
  } else {
    $(".template-generic h2 a").remove();
  }
<% else %>
  $(".template-generic").hide();
  $(".template-mailer").show();
  $(".template-mailer p code:first-child").replaceWith("<%= escape_javascript(display_mailing_mailer(@item.mailer_name)) %>");
<% end %>

<% if @item.list.try(:context_name) %>
  $(".context-name").html("<%= escape_javascript(link_to_context_attributes_overview(@item.list, text: true)) %>");
  var btn = "<%= escape_javascript(link_to_context_attributes_overview(@item.list, class: "btn btn-default")) %>"
  if($(".mailing-start-at .input-group-btn .btn").length == 2) {
    $(".mailing-start-at .input-group-btn .btn:last-child").replaceWith(btn);
  } else {
    $(".mailing-start-at .input-group-btn").append(btn);
  }
<% else %>
  $(".context-name").html("<%= escape_javascript(tw("mailings.no_context")) %>");
  if($(".mailing-start-at .input-group-btn .btn").length == 2) {
    $(".mailing-start-at .input-group-btn .btn:last-child").remove();
  }
<% end %>